### ISSUE TITLE
ver-1.1-todoApp

### ISSUE THREAD

**Issue by arch-spatula** [arch-spatula/todo-app-for-advance#8]
- [x] 스타일링을 추가합니다.
- [x] Heder를 추가합니다.
- [x] 라우팅?

**Comment by arch-spatula** [comment]
```css
* {
    padding: 0;
    border: 0;
    margin: 0;
}
a {text-decoration: none;}
li {list-style: none;}
input {
    appearance: none;
    outline: none;
}
table {border-collapse: collapse;}
```
